### ISSUE TITLE
Is it possible to add a release?

### ISSUE THREAD

**Issue by din14970** [CDoberstein/ExitWaveReconstruction#1]
Hi, I've been looking for a decent exit wave reconstruction code for a while and this looks like a promising project. Also, it's pretty much the only open source exit wave reconstruction package I've found... However, C++ compilation is something that will scare away most users, especially the intended audience of microscopists. So I would like to create a (conda-forge)[https://conda-forge.org/#add_recipe] build recipe for this package so that users with the conda package manager (most microscopists) can easily download and install the binaries for their platform, and then interface with it using python in a jupyter notebook. However, in order to do this, a "release" on github is needed. Could you add a version tag and push it up?

**Comment by din14970** [comment]
You can check out the conda-forge pull request here: https://github.com/conda-forge/staged-recipes/pull/12299, finally was successfull in building for Linux

**Comment by CDoberstein** [comment]
Hi, thank you for the feedback. I just added a release tag to the repository

**Comment by CDoberstein** [comment]
One thing that I would like to point out is that even though you may be able to compile the code on windows (which is something I never tried), it is unlikely that it will work as expected. I don't know how conda-forge works, but you will probably run into some problems with file paths and the shell scripts generated as a part of the program's output. Internally, all file paths are defined with '/' as the delimiting character as opposed to '\\' used by windows. There may also be some other issues, although most of the code should be portable.

**Comment by din14970** [comment]
Yes windows is always annoying. For now I'm only testing the Linux build, then (although still not ideal) windows users may be able to use it with the linux subsystem. In the long run we probably want to run these types of calculations on a server and users would interface with the code through jupyter notebooks in their browser.
